version: "3.7"

volumes:
  data:

services:

  storage:
    image: minio/minio
    command: server --address 0.0.0.0:9000 /data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY    
    volumes:
      - data:/data
